title: Eric's Roleplaying
description: Official site for Eric's Roleplaying
theme: just-the-docs

url: https://eric-delarosa.github.io/ttrpg-site

aux_links:
  "Support Me Here": https://www.google.com
