title: Eric's Roleplaying
description: Official site for Eric's Roleplaying
theme: just-the-docs
color_scheme: dark
url: https://eric-delarosa.github.io/ttrpg-site

aux_links:
  "Support Me Here": https://www.google.com

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
